server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/weatherAPI
    username: postgres
    password: root
    pool:
      initial-size: 1
      max-size: 10
      max-idle-time: 30m
  flyway:
    url: jdbc:postgresql://localhost:5432/weatherAPI
    locations: classpath:db/migration
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}


jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iterations: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: geopokrovskiy

api:
  secret: 1tBvmI2vK64MWfWsRI8IqDYrCibE8oCb
  key-length: 64
  iterations: 16



